// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8FpP_AHTbkcjPoWh31XRgsD4JXGBGQQ',
    appId: '1:329187044859:web:90f88bd732856108696f5e',
    messagingSenderId: '329187044859',
    projectId: 'picom-team',
    authDomain: 'picom-team.firebaseapp.com',
    storageBucket: 'picom-team.firebasestorage.app',
    measurementId: 'G-66VLD3M4GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9l5bjk__wTe3__jORJ2F6WxTeoXEo9fQ',
    appId: '1:329187044859:android:0efdc2cf83479d48696f5e',
    messagingSenderId: '329187044859',
    projectId: 'picom-team',
    storageBucket: 'picom-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJFcd5ojXKyctuaRMAffUgsChb5EZa4w',
    appId: '1:329187044859:ios:18c0081b33a4c184696f5e',
    messagingSenderId: '329187044859',
    projectId: 'picom-team',
    storageBucket: 'picom-team.firebasestorage.app',
    iosClientId: '329187044859-d8t8o288ogjtcv3num3a6e8jbpetav99.apps.googleusercontent.com',
    iosBundleId: 'app.picom.team.piCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJFcd5ojXKyctuaRMAffUgsChb5EZa4w',
    appId: '1:329187044859:ios:18c0081b33a4c184696f5e',
    messagingSenderId: '329187044859',
    projectId: 'picom-team',
    storageBucket: 'picom-team.firebasestorage.app',
    iosClientId: '329187044859-d8t8o288ogjtcv3num3a6e8jbpetav99.apps.googleusercontent.com',
    iosBundleId: 'app.picom.team.piCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc8FpP_AHTbkcjPoWh31XRgsD4JXGBGQQ',
    appId: '1:329187044859:web:ab8f7245e717acce696f5e',
    messagingSenderId: '329187044859',
    projectId: 'picom-team',
    authDomain: 'picom-team.firebaseapp.com',
    storageBucket: 'picom-team.firebasestorage.app',
    measurementId: 'G-S2K4NTFNN1',
  );
}
